site_name: ExecutorGenerator Documentation
repo_url: https://github.com/RT-whs/ExecutorGeneratorDocumentation

nav:
  - Home: index.md
  - About: about.md

theme:
  #name: mkdocs
  name: material   # Pokud chceš použít Material theme, přidej tento řádek a uprav požadované téma
  logo: 'images/WHS_JAG_Robotics_2023_logo.png'  # Cesta k logu (relativní ke složce docs)
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true

# Pro nasazení na GitHub Pages
plugins:
  - search
  - minify:  # Optimalizace souborů HTML
      minify_html: true

# Optional: Custom CSS or JavaScript files
extra_css:
  - 'styles/custom.css'
extra_javascript:
  - 'javascripts/custom.js'
