site_name: Documentation for plc programmers
repo_url: https://github.com/RT-whs/ExecutorGeneratorDocumentation


theme:
  name: material
  palette:
    scheme: whs
  
  logo: 'images/WHS_JAG_Robotics_2023_logo.png'
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.tabs.link
    - header.autohide
    - content.code.copy


markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  
  - toc:
      permalink: true

# For deploying on GitHub pages
plugins:
  - search
  - glightbox



# Optional: Custom CSS or JavaScript files
extra_css:
  - 'stylesheets/custom.css'
extra_javascript:
  - 'javascripts/custom.js'

nav:
  - Home: index.md
  - Documentation: 
    - This documentation: docu/index.md
    - Executor generator: eg/index.md
    - About: about.md

hide:
  - navigation
  - toc
  - footer

