site_name: Documentation for plc programmers
repo_url: https://github.com/RT-whs/ExecutorGeneratorDocumentation


theme:
  name: material
  palette:
    scheme: whs
  
  logo: 'images/WHS_JAG_Robotics_2023_logo.png'
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.tabs.link
    - header.autohide
    - content.code.copy


markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  
  - toc:
      permalink: true

# For deploying on GitHub pages
plugins:
  - search
  - glightbox



# Optional: Custom CSS or JavaScript files
extra_css:
  - 'stylesheets/custom.css'
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/custom.js'

nav:
  - Home: index.md
  - Documentation: 
    - This documentation: docu/index.md
    - Executor generator: eg/index.md
    - Ipm:
      - Data from word files: Ipm/IpmGeneral.md
      - Ipm Results: Ipm/IpmResults.md
    - Magna projects: 
      - Standard: magna/magna.md
      - 231080 - IMM 25:
        - Overview: magna/231080 - IMM 25/Overview.md
        - Robots: magna/231080 - IMM 25/Robots.md
        - IP addresses: magna/231080 - IMM 25/IP addresses.md
    - Tools:
      - AutoHotKey : tools/AutoHotKey/Autohotkey.md
      - Kicad: tools/Kicad/Kicad.md
      - Adapter settings: tools/Adapter_settings/Adapter_settings.md

    - Functions:
      - KUKA:
        - Synchronization: functions/KUKA/Sync.md
      
    - About: about.md

hide:
  - navigation
  - toc
  - footer

