name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main  # Spustí workflow při commitu do větve main (případně upravte název větve)

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Install mkdocs-minify-plugin
        run: pip install mkdocs-minify-plugin
      
      - name: Build and deploy
        run: |
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
